version: "3.9"

services:
  server:
    image: sarptom/mocafi-app-server:latest
    environment:
      - NODE_ENV=development
      - DB_CONNECTION_STRING= ${DB_CONNECTION_STRING}
      - DATABASE_NAME=mocafi
      - PORT=3000
      - APP_URL=${APP_URL}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_SECRET=${DATABASE_SECRET}
      - MONGO_DB_KEY_VAULT_NAMESPACE=${MONGO_DB_KEY_VAULT_NAMESPACE}
      - MASTER_KEY=${MASTER_KEY}
    networks:
      - app-network

  client:
    image: sarptom/mocafi-app-client:latest
    ports:
      - 80:80
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
