version: "3.9"

services:
  server:
    image: sarptom/mocafi-app-server:latest
    environment:
      - NODE_ENV=development
      - DATABASE_URL= ${DATABASE_URL}
      - DATABASE_NAME=mocafi
      - PORT=3000
      - APP_URL=${APP_URL}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_SECRET=${DATABASE_SECRET}
      - MONGO_DB_KEY_VAULT_NAMESPACE=${MONGO_DB_KEY_VAULT_NAMESPACE}
    depends_on:
      - db
    networks:
      - app-network

  client:
    image: sarptom/mocafi-app-client:latest
    ports:
      - "3001:3001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
