FROM node:20-slim

# Set the working directory
WORKDIR /opt/app

# Required for prisma to run
RUN apt-get update && apt-get install -y curl openssl libmongocrypt-dev && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy package.json and package-lock.json
COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

# Install dependencies
RUN npm install 

# Copy the rest of the application code
COPY ./bin ./bin
COPY ./src ./src
COPY ./tsconfig.json ./tsconfig.json
COPY nodemon.json ./nodemon.json

# Start the application
CMD ["npm", "start"]
