version: "3.9"

services:
  db:
    image: mongo:7.0.0
    container_name: application-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    container_name: extension-migrate
    build:
      context: .
      dockerfile: Dockerfile.migrate
    volumes:
      - .:/opt/app
    depends_on:
      - db
